addSbtPlugin("com.typesafe.sbt"   % "sbt-git"               % "1.0.0")
addSbtPlugin("de.heikoseeberger"  % "sbt-header"            % "5.0.0")
addSbtPlugin("com.geirsson"       % "sbt-scalafmt"          % "1.5.1")
addSbtPlugin("com.eed3si9n"       % "sbt-assembly"          % "0.14.9")
addSbtPlugin("com.typesafe.sbt"   % "sbt-native-packager"   % "1.3.17")
